server:
  port: 8081

jwt:
  allowed-cw1-instances:
    cw1: 5436e3e3-0866-4ac1-b0c0-85c6ec8b863b
    cw2: 15436e3e3-0866-4ac1-b0c0-85c6ec8b863b
  audience: 5436e3e3-0866-4ac1-b0c0-85c6ec8b863f
  openid-configuration: classpath:config/openid-configuration.json
  galileo-endpoints:
    qa: http://localhost:8080/jwt/redirectsecureendpoint
    uat: http://localhost:8081/jwt/redirectsecureendpoint
  azr-public-key-url: https://cargowiseb2c01.b2clogin.com/cargowiseb2c01.onmicrosoft.com/b2c_1a_signup_signin/discovery/v2.0/keys
  rdp-web-service: http://localhost:5000/Test/STSM

rsa:
  header-rsa-key-pair: classpath:certs/header-rsa-key-pair.json
  body-rsa-key-pair: classpath:certs/body-rsa-key-pair.json

logging:
  level:
    org.springframework.web: trace
    org.springframework.security: trace


